Messenger.configure do |config|
  config.verify_token      = 'beehive.sceptre.oncolog'
  # config.page_access_token = 'EAAY4gi2TZC6QBAGECh9GqOLOC1vqeeqFoCTFNIHTVRL0CAZC9OCABAcXJprfEnSmkNZAXesabT6kGNYsWmUHG7gZA0hVhbGDJ76rppz6OeTXSssNTGY2rG7ECnaaxjavr9UfojSvPnEDwFoOdr3oyAwXuCobatYh1X60mHiZA8wZDZD'
  config.page_access_token = 'EAAYU0fR3IdkBABYUsmeT5T98gajM6c2zmuE8h2f7S7GLIFPPzxcTUB3CIxXm8cchH2pZBPdiH8zd7WiOb8MJk6XZBi2wSRqqHQBpgkZAeY1yw4ExyXcqwsplKakfidSZBdaeFjyfiZC9OHUS9umJY6fJ8LvBPZBzsoG5xNZCdYqbgZDZD'
end
